version: "3.1"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    networks:
      - confluent
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - confluent
    ports:
      - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_PID=Standard
    - SA_PASSWORD=Pass12&=
    - MSSQL_AGENT_ENABLED=true
  kafka:
    image: confluentinc/cp-kafka
    networks:
      - confluent
    depends_on:
    - zookeeper
    - sqlserver
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
  connector:
    image: debezium/connect:1.3.0.Final
    networks:
      - confluent
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper
      - sqlserver
      - kafka
networks:
  confluent:
    driver: bridge
